### ISSUE TITLE
05-cleaning_it_all_up

### ISSUE THREAD

**Issue by danmtt** [Code-Institute-Solutions/Editor#1]
link to HTML5 img doesn't work?
updated my code with this other one and ok
"https://cdn1.iconfinder.com/data/icons/logotypes/32/badge-html-5-128.png"

Totally new to git so I don't know if this is the right way to warn about bugs or there is another way?
Thanks

**Comment by NielMc** [comment]
@danmtt Yes, that link appears to be broken. You could do a fork, fix the code and then make a pull request.

**Comment by danmtt** [comment]
@NielMc link changed. Now I think I need to close issue...
